#Pretty much constructors for different hit objects, and such. I'm planning on having the game compile .txt files to actually generate stuff
#Though in this case it will be generated by other parts of the game
